import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import './globals.css'

import './assets/css/profile.css'
import './assets/css/login.css'

import './assets/css/navbar.css'
import './assets/css/footer.css'


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
